### ISSUE TITLE
🐛 TypeError: score() got an unexpected keyword argument 'bert'

### ISSUE THREAD

**Issue by Colanim** [facebookresearch/vizseq#5]
# 🐛 Bug

I tried to apply BertScore on my data, but received this error :

> TypeError: score() got an unexpected keyword argument 'bert'

## To reproduce

In configuration, select `BertScore` as metric.  
Refresh the page

**Stack trace/error message**
```
Traceback (most recent call last):
  File "/home/me/.venv/presum/lib/python3.6/site-packages/tornado/web.py", line 1590, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/home/me/workspace/vizseq/vizseq/server.py", line 103, in get
    pd = wv.get_page_data()
  File "/home/me/workspace/vizseq/vizseq/_view/web_view.py", line 158, in get_page_data
    sorting_metric=self.sorting_metric, need_lang_tags=True
  File "/home/me/workspace/vizseq/vizseq/_view/data_view.py", line 132, in get
    for s in metrics
  File "/home/me/workspace/vizseq/vizseq/_view/data_view.py", line 132, in <dictcomp>
    for s in metrics
  File "/home/me/workspace/vizseq/vizseq/_view/data_view.py", line 130, in <dictcomp>
    for m, hh in cur_hypo.items()
  File "/home/me/workspace/vizseq/vizseq/scorers/bert_score.py", line 28, in score
    no_idf=True, verbose=self.verbose
TypeError: score() got an unexpected keyword argument 'bert'
```

## Expected Behavior
Able to see `BertScore`.

## System information
- VizSeq Version : **0.1.2**
- Python version : **3.6.8**
- Operating system : **Ubuntu 16.04**

**Comment by kahne** [comment]
Thanks for reporting! The latest `bert-score` 0.2 has updated the API while VizSeq was still using the 0.1 one. Now fixed in #7.
