### ISSUE TITLE
[Bug] pip install vizseq error

### ISSUE THREAD

**Issue by xsfang** [facebookresearch/vizseq#84]
# 🐛 Bug

I am installing vizseq in a colab notebook and got an error:

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchaudio 2.3.0+cu121 requires torch==2.3.0, but you have torch 1.13.1 which is incompatible.
torchtext 0.18.0 requires torch>=2.3.0, but you have torch 1.13.1 which is incompatible.
torchvision 0.18.0+cu121 requires torch==2.3.0, but you have torch 1.13.1 which is incompatible.

How to solve this problem?
Thanks,

**Comment by ai-nikolai** [comment]
I am also getting this error:
```
ERROR: Exception:
Traceback (most recent call last):
  File "/home/ubuntu/env/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 165, in exc_logging_wrapper
    status = run_func(*args)
  File "/home/ubuntu/env/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "/home/ubuntu/env/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 389, in run
    to_install = resolver.get_installation_order(requirement_set)
  File "/home/ubuntu/env/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 188, in get_installation_order
    weights = get_topological_weights(
  File "/home/ubuntu/env/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 276, in get_topological_weights
    assert len(weights) == expected_node_count
AssertionError
```

**Comment by ai-nikolai** [comment]
@zpao @niavasha @jailby

**Comment by kahne** [comment]
Resolved on the latest main branch by #109: plain pip install vizseq no longer installs or pins PyTorch because the heavy embedding dependencies were moved to the optional embeddings extra. This avoids replacing Colab’s preinstalled Torch during a base install. Note that the embeddings extra still requires its dependency set separately.
